// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAIzmSd682Vz4XluMBZ8NTCDbGhpPJV4M',
    appId: '1:113988307458:web:51157a26a19b84d5aa351b',
    messagingSenderId: '113988307458',
    projectId: 'final-flutter-project-a53b5',
    authDomain: 'final-flutter-project-a53b5.firebaseapp.com',
    storageBucket: 'final-flutter-project-a53b5.firebasestorage.app',
    measurementId: 'G-LBBMT8MBGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8vdi20SeBSkH6-5b8yt2KB8tgMhWZ69U',
    appId: '1:113988307458:android:36017293e88af233aa351b',
    messagingSenderId: '113988307458',
    projectId: 'final-flutter-project-a53b5',
    storageBucket: 'final-flutter-project-a53b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyPd4YDh7MmLAISC1FvsZ9pq9rqA49k2A',
    appId: '1:113988307458:ios:9242cf34c968e488aa351b',
    messagingSenderId: '113988307458',
    projectId: 'final-flutter-project-a53b5',
    storageBucket: 'final-flutter-project-a53b5.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyPd4YDh7MmLAISC1FvsZ9pq9rqA49k2A',
    appId: '1:113988307458:ios:9242cf34c968e488aa351b',
    messagingSenderId: '113988307458',
    projectId: 'final-flutter-project-a53b5',
    storageBucket: 'final-flutter-project-a53b5.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAIzmSd682Vz4XluMBZ8NTCDbGhpPJV4M',
    appId: '1:113988307458:web:0b28a20f44500c14aa351b',
    messagingSenderId: '113988307458',
    projectId: 'final-flutter-project-a53b5',
    authDomain: 'final-flutter-project-a53b5.firebaseapp.com',
    storageBucket: 'final-flutter-project-a53b5.firebasestorage.app',
    measurementId: 'G-596GRVL8RB',
  );

}